# Quantify Annotator Agreement with Krippendorff's alpha 
> "Calculate inter-annotator and individual-annotator agreement in a dataset"

- toc: true
- badges: true
- comments: true
- author: Anish Dalal
- categories: [Data, ML]

## Inter-Annotator Agreement

The wisdom of crowds usually results in answers more accurate than any one individual. So a high-level of overall dataset agreement or Krippendorff alpha score is an indicator that the dataset is reliable for model training.
Krippendorff's alpha is a metric used in the social sciences for measure level of agreement in surveys or census data. The metric ranges from [-1, 1] and a score greater than 0.8 indicates high agreement.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

Create a random dataframe of annotations. Each row is a task and each column is an annotator. There are five label types ranging from 1 through 4. A 0 indicates that the specific task was not labeled by the annotator.

In [2]:
annotators = ["a", "b", "c", "d", "e"]
tasks = [f"Task {i}" for i in np.arange(11) + 1]

# create a random dataframe of annotations 
annotations_mat = np.random.randint(0,5,size=(11,5))
annotations_df = pd.DataFrame(columns=annotators, index=tasks, data=annotations_mat)
annotations_df

         a  b  c  d  e
Task 1   3  4  2  4  4
Task 2   1  2  2  2  4
Task 3   3  2  4  1  3
Task 4   1  3  4  0  3
Task 5   1  4  3  0  0
Task 6   2  2  1  3  3
Task 7   2  3  3  0  2
Task 8   4  2  4  0  1
Task 9   3  0  3  1  1
Task 10  0  1  4  1  3
Task 11  3  3  3  4  2

### Expected Agreement

In [3]:
counts_df = annotations_df.apply(pd.Series.value_counts, axis=1).drop(columns=[0]).fillna(0)
counts_per_label = counts_df.sum(axis=0)
counts_per_label

1    10.0
2    11.0
3    16.0
4    11.0
dtype: float64

In [4]:
total_annotations =  counts_df.sum().sum()

In [5]:
label_relative_frequency = counts_per_label / counts_per_label.sum()
label_relative_frequency

1    0.208333
2    0.229167
3    0.333333
4    0.229167
dtype: float64

In [13]:
expected_agreement = np.sum(label_relative_frequency ** 2)
expected_agreement

0.2595486111111111

### Actual Agreement

In [14]:
counts_df = annotations_df.apply(pd.Series.value_counts, axis=1).drop(columns=[0]).fillna(0)
counts_df

           1    2    3    4
Task 1   0.0  1.0  1.0  3.0
Task 2   1.0  3.0  0.0  1.0
Task 3   1.0  1.0  2.0  1.0
Task 4   1.0  0.0  2.0  1.0
Task 5   1.0  0.0  1.0  1.0
Task 6   1.0  2.0  2.0  0.0
Task 7   0.0  2.0  2.0  0.0
Task 8   1.0  1.0  0.0  2.0
Task 9   2.0  0.0  2.0  0.0
Task 10  2.0  0.0  1.0  1.0
Task 11  0.0  1.0  3.0  1.0

In [15]:
avg_annotations_per_task = total_annotations / len(tasks)

In [16]:
counts_per_task = counts_df.sum(axis=1)

In [17]:
sum_pairwise_agreements = (counts_df * (counts_df - 1)).sum(axis=1)

In [18]:
average_agreement = np.mean(sum_pairwise_agreements / (avg_annotations_per_task * (counts_per_task - 1)))

In [19]:
average_agreement

0.22222222222222224

In [20]:
k_alpha = (average_agreement - expected_agreement) / (1 - expected_agreement)

In [21]:
k_alpha

-0.050410316529894465